import type { CheckIn, EscalationLog, EscalationRule, GoalRecord, NotificationLog, Profile, QuarterlyUpdate } from './types';

export const demoProfiles: Profile[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    full_name: 'Alex Mercer',
    email: 'employee@nexus.demo',
    role: 'employee',
    job_title: 'Frontend Engineer',
    department: 'Product Engineering',
    manager_id: '22222222-2222-2222-2222-222222222222',
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    full_name: 'Sarah Connor',
    email: 'manager@nexus.demo',
    role: 'manager',
    job_title: 'Engineering Manager',
    department: 'Product Engineering',
    manager_id: '33333333-3333-3333-3333-333333333333',
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    full_name: 'Priya Rao',
    email: 'admin@nexus.demo',
    role: 'admin',
    job_title: 'People Ops Admin',
    department: 'Business Excellence',
    manager_id: null,
  },
];

export const demoCredentials = [
  { label: 'Employee', email: 'employee@nexus.demo', password: 'NexusEmp@2026' },
  { label: 'Manager', email: 'manager@nexus.demo', password: 'NexusMgr@2026' },
  { label: 'Admin', email: 'admin@nexus.demo', password: 'NexusAdmin@2026' },
];

export const demoGoals: GoalRecord[] = [
  {
    id: 'hub-1',
    owner_id: demoProfiles[0].id,
    parent_goal_id: null,
    shared_goal_id: null,
    primary_owner_id: null,
    title: 'Increase Q3 Software Revenue',
    description: 'Departmental revenue KPI cascaded to Product Engineering for the active performance cycle.',
    category: 'Revenue Growth',
    uom_type: 'Min (Higher is better)',
    target_value: '5000000',
    baseline_value: 3500000,
    weightage: 40,
    status: 'approved',
    progress: 65,
    position_x: 400,
    position_y: 50,
    is_hub: true,
    is_shared: false,
    locked: true,
  },
  {
    id: 'goal-1',
    owner_id: demoProfiles[0].id,
    parent_goal_id: 'hub-1',
    shared_goal_id: 'shared-portal-launch',
    primary_owner_id: demoProfiles[1].id,
    title: 'Launch Enterprise Portal',
    description: 'Ship the enterprise customer portal with SSO, usage analytics, and onboarding checklist completed before the committed deadline.',
    category: 'Product Innovation',
    uom_type: 'Timeline',
    target_value: '2026-06-30',
    baseline_value: null,
    weightage: 20,
    status: 'approved',
    progress: 100,
    position_x: 200,
    position_y: 250,
    is_hub: false,
    is_shared: true,
    locked: true,
  },
  {
    id: 'goal-2',
    owner_id: demoProfiles[0].id,
    parent_goal_id: 'hub-1',
    shared_goal_id: null,
    primary_owner_id: null,
    title: 'Reduce Cloud Hosting Costs',
    description: 'Reduce avoidable idle infrastructure spend while preserving production reliability and release velocity.',
    category: 'Operational Excellence',
    uom_type: 'Max (Lower is better)',
    target_value: '15',
    baseline_value: 100,
    weightage: 20,
    status: 'submitted',
    progress: 30,
    position_x: 600,
    position_y: 250,
    is_hub: false,
    is_shared: false,
    locked: false,
  },
  {
    id: 'goal-3',
    owner_id: demoProfiles[0].id,
    parent_goal_id: 'hub-1',
    shared_goal_id: null,
    primary_owner_id: null,
    title: 'Improve Lighthouse Performance Score',
    description: 'Raise production Lighthouse performance score through bundle splitting, image optimization, and caching improvements.',
    category: 'Product Innovation',
    uom_type: 'Min (Higher is better)',
    target_value: '95',
    baseline_value: 72,
    weightage: 20,
    status: 'draft',
    progress: 72,
    position_x: 410,
    position_y: 430,
    is_hub: false,
    is_shared: false,
    locked: false,
  },
];

export const demoQuarterlyUpdates: QuarterlyUpdate[] = [
  {
    id: 'update-1',
    goal_id: 'goal-1',
    quarter: 'Q4 2025',
    actual_value: '2025-12-20',
    achievement_status: 'Completed',
    computed_score: 100,
    comment: 'Shipped before target date.',
    created_at: '2025-12-20T10:30:00Z',
  },
  {
    id: 'update-2',
    goal_id: 'goal-2',
    quarter: 'Q4 2025',
    actual_value: '23',
    achievement_status: 'On Track',
    computed_score: 65,
    comment: 'Savings started after cloud rightsizing.',
    created_at: '2025-12-28T10:30:00Z',
  },
  {
    id: 'update-3',
    goal_id: 'goal-1',
    quarter: 'Q1 2026',
    actual_value: '2026-03-25',
    achievement_status: 'Completed',
    computed_score: 100,
    comment: 'Portal rollout remained on plan.',
    created_at: '2026-03-25T10:30:00Z',
  },
  {
    id: 'update-4',
    goal_id: 'goal-2',
    quarter: 'Q1 2026',
    actual_value: '18',
    achievement_status: 'On Track',
    computed_score: 83,
    comment: 'Reserved instances improved cost curve.',
    created_at: '2026-03-29T10:30:00Z',
  },
];

export const demoCheckIns: CheckIn[] = [
  {
    id: 'checkin-1',
    employee_id: demoProfiles[0].id,
    manager_id: demoProfiles[1].id,
    comment: 'Reviewed cloud cost blockers and agreed on reserved instance cleanup before Q2 close.',
    created_at: '2026-04-16T10:30:00Z',
  },
];

export const demoAuditLogs = [
  {
    id: 'audit-1',
    actor_id: demoProfiles[1].id,
    action: 'APPROVE_GOAL',
    entity_type: 'goal',
    entity_id: 'goal-1',
    metadata: { status: { from: 'submitted', to: 'approved' } },
    created_at: '2026-04-17T10:30:00Z',
  },
];

export const demoNotificationLogs: NotificationLog[] = [
  {
    id: 'notification-1',
    recipient_id: demoProfiles[1].id,
    channel: 'teams',
    event_type: 'goal_submitted',
    title: 'Goal sheet submitted',
    message: 'Alex Mercer submitted Q2 goals for manager approval.',
    deep_link: '/manager?employee=11111111-1111-1111-1111-111111111111',
    status: 'sent',
    created_at: '2026-05-04T09:30:00Z',
  },
  {
    id: 'notification-2',
    recipient_id: demoProfiles[0].id,
    channel: 'email',
    event_type: 'goal_approved',
    title: 'Goals approved',
    message: 'Your Launch Enterprise Portal goal has been approved and locked.',
    deep_link: '/',
    status: 'sent',
    created_at: '2026-05-05T11:30:00Z',
  },
  {
    id: 'notification-3',
    recipient_id: demoProfiles[1].id,
    channel: 'email',
    event_type: 'checkin_reminder',
    title: 'Q2 check-in reminder',
    message: 'Complete quarterly check-ins for direct reports before the active window closes.',
    deep_link: '/manager',
    status: 'queued',
    created_at: '2026-05-12T08:30:00Z',
  },
];

export const demoEscalationRules: EscalationRule[] = [
  {
    id: 'rule-1',
    name: 'Goal submission overdue',
    trigger_type: 'goal_submission_overdue',
    threshold_days: 5,
    first_notify_role: 'employee',
    second_notify_role: 'manager',
    final_notify_role: 'admin',
    active: true,
  },
  {
    id: 'rule-2',
    name: 'Manager approval overdue',
    trigger_type: 'manager_approval_overdue',
    threshold_days: 3,
    first_notify_role: 'manager',
    second_notify_role: 'admin',
    final_notify_role: 'admin',
    active: true,
  },
  {
    id: 'rule-3',
    name: 'Quarterly check-in overdue',
    trigger_type: 'checkin_overdue',
    threshold_days: 7,
    first_notify_role: 'employee',
    second_notify_role: 'manager',
    final_notify_role: 'admin',
    active: true,
  },
];

export const demoEscalationLogs: EscalationLog[] = [
  {
    id: 'escalation-1',
    rule_id: 'rule-2',
    employee_id: demoProfiles[0].id,
    manager_id: demoProfiles[1].id,
    level: 1,
    message: 'Reduce Cloud Hosting Costs is pending manager approval beyond the configured threshold.',
    status: 'open',
    created_at: '2026-05-09T09:00:00Z',
  },
];
